import type { ApiProxy } from '@deepseek-ai/dsh-host-apiproxy';
import { type ImportPreview, type ProjectSnapshot, type SddAction, type StageRun } from './protocol.ts';
import { type SddIdentifierRegistry, type SddSourceRegistry } from './extensions.ts';
import { GitDevelopmentService } from './git-service.ts';
import type { StageSessionController } from './session-controller.ts';
export declare class SddProjectService {
    private readonly api;
    private readonly sourceRegistry?;
    private readonly identifierRegistry?;
    private readonly sessionController?;
    private readonly git;
    constructor(api: ApiProxy, sourceRegistry?: SddSourceRegistry | undefined, identifierRegistry?: SddIdentifierRegistry | undefined, sessionController?: StageSessionController | undefined, git?: GitDevelopmentService);
    private workspace;
    execute(action: SddAction): Promise<ProjectSnapshot | ImportPreview | {
        prompt: string;
        run?: StageRun;
    }>;
    initialize(workspaceId: string): Promise<void>;
    private reinitialize;
    snapshot(workspaceId: string): Promise<ProjectSnapshot>;
    private listConnectors;
    private listWorkItems;
    private createDraft;
    private nextKey;
    private allocateKey;
    private listSources;
    private previewSourceImport;
    private writeSourceSnapshot;
    private applySourceImport;
    private resolveWorkItemRemoval;
    private template;
    private hasCurrentChangeEvidence;
    private accept;
    private context;
    private bindSession;
    private syncRun;
    private completeRun;
    private listRuns;
    private writeRun;
    private bindRuntime;
    private requireSnapshot;
    private requireArtifact;
    private emptyDashboard;
    private dashboard;
}
