/**
 * Generate the client build stamp module.
 *
 * The marker lets a running page report which client bundle it actually loaded, so a stale
 * `link:` install (the app was not restarted after a rebuild) becomes visible instead of silent.
 * The file is rewritten on every build; the value is the build time in ISO-8601.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const target = join(packageRoot, 'src', 'client', 'build-stamp.ts')
const stamp = new Date().toISOString()

await mkdir(dirname(target), { recursive: true })
await writeFile(target, `// Generated by scripts/build-stamp.mjs — do not edit.\nexport const CLIENT_BUILD = ${JSON.stringify(stamp)}\n`)
console.log(`client build stamp: ${stamp}`)
